// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtjbjypjlodzhjbdfuyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0amJqeXBqbG9kemhqYmRmdXljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNjk3MDgsImV4cCI6MjA2Nzk0NTcwOH0.OdKBg6-WAGcz3UpSBmKrolzY5DBh4H_DBc8_f7Xdc_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});